// generated by stringer -type=Day; DO NOT EDIT

package doomsday

import "fmt"

const _Day_name = "SundayMondayTuesdayWednesdayThursdayFridaySaturday"

var _Day_index = [...]uint8{0, 6, 12, 19, 28, 36, 42, 50}

func (i Day) String() string {
	if i < 0 || i+1 >= Day(len(_Day_index)) {
		return fmt.Sprintf("Day(%d)", i)
	}
	return _Day_name[_Day_index[i]:_Day_index[i+1]]
}
