// generated by stringer -type=dayOfWeek; DO NOT EDIT

package doomsday

import "fmt"

const _dayOfWeek_name = "SundayMondayTuesdayWednesdayThursdayFridaySaturday"

var _dayOfWeek_index = [...]uint8{0, 6, 12, 19, 28, 36, 42, 50}

func (i dayOfWeek) String() string {
	if i < 0 || i+1 >= dayOfWeek(len(_dayOfWeek_index)) {
		return fmt.Sprintf("dayOfWeek(%d)", i)
	}
	return _dayOfWeek_name[_dayOfWeek_index[i]:_dayOfWeek_index[i+1]]
}
